function clln = CodeComplex(this)
    %---------------------------------------------------------------------------
    % Usage:
    %    clln = this.CodeComplex()
    % Description:
    %    Return a `Collection` object containing the faces of the simplicial
    %    complex generated by the supports of the codeword vectors.
    %---------------------------------------------------------------------------
    
    clln = SimplicialComplex(this.Words);
end